name: Lock Inactive Issues

on:
  schedule:
    # Run at 00:00 every day
    - cron: '0 0 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@0bd2bee03a032325cada4c75f0a1388bb2661fb8
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
